apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zqgal6ydl-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zqgal6ydl-java-springboot-gitops